version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: email_user
      POSTGRES_PASSWORD: email_password
      POSTGRES_DB: email_marketing_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U email_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://email_user:email_password@db:5432/email_marketing_db
      REDIS_URL: redis://redis:6379
      SECRET_KEY: your-secret-key-change-in-production
      ENVIRONMENT: development
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  celery:
    build: .
    environment:
      DATABASE_URL: postgresql://email_user:email_password@db:5432/email_marketing_db
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app/app
    command: celery -A app.tasks worker --loglevel=info

  celery-beat:
    build: .
    environment:
      DATABASE_URL: postgresql://email_user:email_password@db:5432/email_marketing_db
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app/app
    command: celery -A app.tasks beat --loglevel=info

volumes:
  postgres_data: